# Generated by Django 4.0.5 on 2022-06-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=15)),
                ("publish_date", models.DateTimeField(verbose_name="date published")),
                ("body_content", models.CharField(max_length=500)),
            ],
        ),
    ]
